./a.out 0 2>> output.txt 1>> output.txt 
./a.out 0 2>> output.txt 1>> output.txt
./a.out 0 2>> output.txt 1>> output.txt
./a.out 0 2>> output.txt 1>> output.txt
./a.out 0 2>> output.txt 1>> output.txt
./a.out 1 2>> output.txt 1>> output.txt
./a.out 1 2>> output.txt 1>> output.txt
./a.out 1 2>> output.txt 1>> output.txt
./a.out 1 2>> output.txt 1>> output.txt
./a.out 1 2>> output.txt 1>> output.txt
./a.out 2 2>> output.txt 1>> output.txt
./a.out 2 2>> output.txt 1>> output.txt
./a.out 2 2>> output.txt 1>> output.txt
./a.out 2 2>> output.txt 1>> output.txt
./a.out 2 2>> output.txt 1>> output.txt
./a.out 3 2>> output.txt 1>> output.txt
./a.out 3 2>> output.txt 1>> output.txt
./a.out 3 2>> output.txt 1>> output.txt
./a.out 3 2>> output.txt 1>> output.txt
./a.out 3 2>> output.txt 1>> output.txt
./a.out 4 2>> output.txt 1>> output.txt
./a.out 4 2>> output.txt 1>> output.txt
./a.out 4 2>> output.txt 1>> output.txt
./a.out 4 2>> output.txt 1>> output.txt
./a.out 4 2>> output.txt 1>> output.txt
